language: java
jdk: oraclejdk11

services:
  - postgresql

before_script:
  - psql -c 'create database springchess; create role springchess with login password \'springchess\'; alter user springchess createdb;' -U postgres